# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/axes_tabw.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Axes_tabwidget(object):
    def setupUi(self, Axes_tabwidget):
        Axes_tabwidget.setObjectName("Axes_tabwidget")
        Axes_tabwidget.resize(565, 391)
        self.gridLayout_3 = QtWidgets.QGridLayout(Axes_tabwidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Axes_tabwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.AxesRange_tab = QtWidgets.QWidget()
        self.AxesRange_tab.setObjectName("AxesRange_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.AxesRange_tab)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Yrange_checkBox = QtWidgets.QCheckBox(self.AxesRange_tab)
        self.Yrange_checkBox.setObjectName("Yrange_checkBox")
        self.gridLayout_2.addWidget(self.Yrange_checkBox, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.Xrange_to_lineEdit = QtWidgets.QLineEdit(self.AxesRange_tab)
        self.Xrange_to_lineEdit.setEnabled(False)
        self.Xrange_to_lineEdit.setObjectName("Xrange_to_lineEdit")
        self.gridLayout_2.addWidget(self.Xrange_to_lineEdit, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 4, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.AxesRange_tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 1, 1, 1, 4)
        self.label_23 = QtWidgets.QLabel(self.AxesRange_tab)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 3, 2, 1, 1)
        self.Yrange_to_lineEdit = QtWidgets.QLineEdit(self.AxesRange_tab)
        self.Yrange_to_lineEdit.setEnabled(False)
        self.Yrange_to_lineEdit.setObjectName("Yrange_to_lineEdit")
        self.gridLayout_2.addWidget(self.Yrange_to_lineEdit, 3, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.AxesRange_tab)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 2, 1, 1)
        self.Yrange_from_lineEdit = QtWidgets.QLineEdit(self.AxesRange_tab)
        self.Yrange_from_lineEdit.setEnabled(False)
        self.Yrange_from_lineEdit.setObjectName("Yrange_from_lineEdit")
        self.gridLayout_2.addWidget(self.Yrange_from_lineEdit, 3, 1, 1, 1)
        self.Xrange_from_lineEdit = QtWidgets.QLineEdit(self.AxesRange_tab)
        self.Xrange_from_lineEdit.setEnabled(False)
        self.Xrange_from_lineEdit.setObjectName("Xrange_from_lineEdit")
        self.gridLayout_2.addWidget(self.Xrange_from_lineEdit, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.AxesRange_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 1, 0, 1, 1)
        self.Xrange_checkBox = QtWidgets.QCheckBox(self.AxesRange_tab)
        self.Xrange_checkBox.setObjectName("Xrange_checkBox")
        self.gridLayout_2.addWidget(self.Xrange_checkBox, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.LogX_checkBox = QtWidgets.QCheckBox(self.AxesRange_tab)
        self.LogX_checkBox.setObjectName("LogX_checkBox")
        self.gridLayout.addWidget(self.LogX_checkBox, 1, 0, 1, 1)
        self.LogY_checkBox = QtWidgets.QCheckBox(self.AxesRange_tab)
        self.LogY_checkBox.setObjectName("LogY_checkBox")
        self.gridLayout.addWidget(self.LogY_checkBox, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.tabWidget.addTab(self.AxesRange_tab, "")
        self.AxesLabels_tab = QtWidgets.QWidget()
        self.AxesLabels_tab.setObjectName("AxesLabels_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.AxesLabels_tab)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.AxesLabels_gridLayout = QtWidgets.QGridLayout()
        self.AxesLabels_gridLayout.setContentsMargins(11, 11, 11, 11)
        self.AxesLabels_gridLayout.setSpacing(6)
        self.AxesLabels_gridLayout.setObjectName("AxesLabels_gridLayout")
        self.YLabeloffsetdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesLabels_tab)
        self.YLabeloffsetdoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YLabeloffsetdoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YLabeloffsetdoubleSpinBox.setObjectName("YLabeloffsetdoubleSpinBox")
        self.AxesLabels_gridLayout.addWidget(self.YLabeloffsetdoubleSpinBox, 2, 3, 1, 1)
        self.Labelslabel = QtWidgets.QLabel(self.AxesLabels_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Labelslabel.setFont(font)
        self.Labelslabel.setObjectName("Labelslabel")
        self.AxesLabels_gridLayout.addWidget(self.Labelslabel, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.AxesLabels_tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.AxesLabels_gridLayout.addWidget(self.line_2, 0, 1, 1, 3)
        self.label = QtWidgets.QLabel(self.AxesLabels_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.AxesLabels_gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.XLabeloffsetdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesLabels_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XLabeloffsetdoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.XLabeloffsetdoubleSpinBox.setSizePolicy(sizePolicy)
        self.XLabeloffsetdoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XLabeloffsetdoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XLabeloffsetdoubleSpinBox.setObjectName("XLabeloffsetdoubleSpinBox")
        self.AxesLabels_gridLayout.addWidget(self.XLabeloffsetdoubleSpinBox, 1, 3, 1, 1)
        self.YLabellineEdit = QtWidgets.QLineEdit(self.AxesLabels_tab)
        self.YLabellineEdit.setObjectName("YLabellineEdit")
        self.AxesLabels_gridLayout.addWidget(self.YLabellineEdit, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.AxesLabels_tab)
        self.label_2.setObjectName("label_2")
        self.AxesLabels_gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.YLabellabel = QtWidgets.QLabel(self.AxesLabels_tab)
        self.YLabellabel.setObjectName("YLabellabel")
        self.AxesLabels_gridLayout.addWidget(self.YLabellabel, 2, 0, 1, 1)
        self.XLabellineEdit = QtWidgets.QLineEdit(self.AxesLabels_tab)
        self.XLabellineEdit.setObjectName("XLabellineEdit")
        self.AxesLabels_gridLayout.addWidget(self.XLabellineEdit, 1, 1, 1, 1)
        self.XLabellabel = QtWidgets.QLabel(self.AxesLabels_tab)
        self.XLabellabel.setObjectName("XLabellabel")
        self.AxesLabels_gridLayout.addWidget(self.XLabellabel, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.AxesLabels_gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.tabWidget.addTab(self.AxesLabels_tab, "")
        self.AxesTics_tab = QtWidgets.QWidget()
        self.AxesTics_tab.setObjectName("AxesTics_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.AxesTics_tab)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Tics_gridLayout = QtWidgets.QGridLayout()
        self.Tics_gridLayout.setContentsMargins(11, 11, 11, 11)
        self.Tics_gridLayout.setSpacing(6)
        self.Tics_gridLayout.setObjectName("Tics_gridLayout")
        self.XticsBottom_checkBox = QtWidgets.QCheckBox(self.AxesTics_tab)
        self.XticsBottom_checkBox.setChecked(True)
        self.XticsBottom_checkBox.setObjectName("XticsBottom_checkBox")
        self.Tics_gridLayout.addWidget(self.XticsBottom_checkBox, 1, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.AxesTics_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.Tics_gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.XticsMinor_checkBox = QtWidgets.QCheckBox(self.AxesTics_tab)
        self.XticsMinor_checkBox.setObjectName("XticsMinor_checkBox")
        self.Tics_gridLayout.addWidget(self.XticsMinor_checkBox, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.AxesTics_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Tics_gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.XticsMinorLength_label = QtWidgets.QLabel(self.AxesTics_tab)
        self.XticsMinorLength_label.setEnabled(False)
        self.XticsMinorLength_label.setObjectName("XticsMinorLength_label")
        self.Tics_gridLayout.addWidget(self.XticsMinorLength_label, 2, 3, 1, 1)
        self.Xtics_lineEdit = QtWidgets.QLineEdit(self.AxesTics_tab)
        self.Xtics_lineEdit.setObjectName("Xtics_lineEdit")
        self.Tics_gridLayout.addWidget(self.Xtics_lineEdit, 1, 1, 1, 2)
        self.XticsMinor_spinBox = QtWidgets.QSpinBox(self.AxesTics_tab)
        self.XticsMinor_spinBox.setEnabled(False)
        self.XticsMinor_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsMinor_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsMinor_spinBox.setObjectName("XticsMinor_spinBox")
        self.Tics_gridLayout.addWidget(self.XticsMinor_spinBox, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.AxesTics_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.Tics_gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.XticsLength_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.XticsLength_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsLength_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsLength_doubleSpinBox.setProperty("value", 5.0)
        self.XticsLength_doubleSpinBox.setObjectName("XticsLength_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.XticsLength_doubleSpinBox, 1, 4, 1, 1)
        self.YticsRight_checkBox = QtWidgets.QCheckBox(self.AxesTics_tab)
        self.YticsRight_checkBox.setChecked(True)
        self.YticsRight_checkBox.setObjectName("YticsRight_checkBox")
        self.Tics_gridLayout.addWidget(self.YticsRight_checkBox, 4, 5, 1, 1)
        self.YticsMinor_checkBox = QtWidgets.QCheckBox(self.AxesTics_tab)
        self.YticsMinor_checkBox.setObjectName("YticsMinor_checkBox")
        self.Tics_gridLayout.addWidget(self.YticsMinor_checkBox, 5, 1, 1, 1)
        self.XticsOffset_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.XticsOffset_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsOffset_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsOffset_doubleSpinBox.setObjectName("XticsOffset_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.XticsOffset_doubleSpinBox, 3, 2, 1, 1)
        self.XticsTop_checkBox = QtWidgets.QCheckBox(self.AxesTics_tab)
        self.XticsTop_checkBox.setChecked(True)
        self.XticsTop_checkBox.setObjectName("XticsTop_checkBox")
        self.Tics_gridLayout.addWidget(self.XticsTop_checkBox, 1, 5, 1, 1)
        self.YticsMinorLength_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.YticsMinorLength_doubleSpinBox.setEnabled(False)
        self.YticsMinorLength_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsMinorLength_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsMinorLength_doubleSpinBox.setObjectName("YticsMinorLength_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.YticsMinorLength_doubleSpinBox, 5, 4, 1, 1)
        self.YticsLength_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.YticsLength_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsLength_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsLength_doubleSpinBox.setProperty("value", 5.0)
        self.YticsLength_doubleSpinBox.setObjectName("YticsLength_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.YticsLength_doubleSpinBox, 4, 4, 1, 1)
        self.YticsOffset_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.YticsOffset_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsOffset_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsOffset_doubleSpinBox.setObjectName("YticsOffset_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.YticsOffset_doubleSpinBox, 6, 2, 1, 1)
        self.YticsMinor_spinBox = QtWidgets.QSpinBox(self.AxesTics_tab)
        self.YticsMinor_spinBox.setEnabled(False)
        self.YticsMinor_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsMinor_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsMinor_spinBox.setObjectName("YticsMinor_spinBox")
        self.Tics_gridLayout.addWidget(self.YticsMinor_spinBox, 5, 2, 1, 1)
        self.YticsMinorLength_label = QtWidgets.QLabel(self.AxesTics_tab)
        self.YticsMinorLength_label.setEnabled(False)
        self.YticsMinorLength_label.setObjectName("YticsMinorLength_label")
        self.Tics_gridLayout.addWidget(self.YticsMinorLength_label, 5, 3, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.AxesTics_tab)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.Tics_gridLayout.addWidget(self.checkBox_4, 4, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.AxesTics_tab)
        self.label_9.setObjectName("label_9")
        self.Tics_gridLayout.addWidget(self.label_9, 4, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.AxesTics_tab)
        self.label_8.setObjectName("label_8")
        self.Tics_gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.AxesTics_tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Tics_gridLayout.addWidget(self.line_3, 0, 1, 1, 6)
        self.Ytics_lineEdit = QtWidgets.QLineEdit(self.AxesTics_tab)
        self.Ytics_lineEdit.setObjectName("Ytics_lineEdit")
        self.Tics_gridLayout.addWidget(self.Ytics_lineEdit, 4, 1, 1, 2)
        self.XticsMinorLength_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.XticsMinorLength_doubleSpinBox.setEnabled(False)
        self.XticsMinorLength_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsMinorLength_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsMinorLength_doubleSpinBox.setObjectName("XticsMinorLength_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.XticsMinorLength_doubleSpinBox, 2, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.AxesTics_tab)
        self.label_10.setObjectName("label_10")
        self.Tics_gridLayout.addWidget(self.label_10, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.AxesTics_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.Tics_gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.Tics_gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.tabWidget.addTab(self.AxesTics_tab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Axes_tabwidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Axes_tabwidget)

    def retranslateUi(self, Axes_tabwidget):
        _translate = QtCore.QCoreApplication.translate
        self.Yrange_checkBox.setText(_translate("Axes_tabwidget", "Y Range:"))
        self.label_23.setText(_translate("Axes_tabwidget", "  :  "))
        self.label_22.setText(_translate("Axes_tabwidget", "  :  "))
        self.label_21.setText(_translate("Axes_tabwidget", "AXIS RANGE"))
        self.Xrange_checkBox.setText(_translate("Axes_tabwidget", "X Range:"))
        self.LogX_checkBox.setText(_translate("Axes_tabwidget", "Logaritmic X axis"))
        self.LogY_checkBox.setText(_translate("Axes_tabwidget", "Logaritmic Y axis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AxesRange_tab), _translate("Axes_tabwidget", "Range"))
        self.Labelslabel.setText(_translate("Axes_tabwidget", "LABELS"))
        self.label.setText(_translate("Axes_tabwidget", "Offset"))
        self.label_2.setText(_translate("Axes_tabwidget", "Offset"))
        self.YLabellabel.setText(_translate("Axes_tabwidget", " Y label:"))
        self.XLabellabel.setText(_translate("Axes_tabwidget", " X label:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AxesLabels_tab), _translate("Axes_tabwidget", "Labels"))
        self.XticsBottom_checkBox.setText(_translate("Axes_tabwidget", "Bottom"))
        self.label_4.setText(_translate("Axes_tabwidget", "  X tics:"))
        self.XticsMinor_checkBox.setText(_translate("Axes_tabwidget", " Minor tics"))
        self.label_3.setText(_translate("Axes_tabwidget", "TICS      "))
        self.XticsMinorLength_label.setText(_translate("Axes_tabwidget", "Length"))
        self.label_6.setText(_translate("Axes_tabwidget", "Length"))
        self.YticsRight_checkBox.setText(_translate("Axes_tabwidget", "Left"))
        self.YticsMinor_checkBox.setText(_translate("Axes_tabwidget", "Minor tics"))
        self.XticsTop_checkBox.setText(_translate("Axes_tabwidget", "Top"))
        self.YticsMinorLength_label.setText(_translate("Axes_tabwidget", "Length"))
        self.checkBox_4.setText(_translate("Axes_tabwidget", "Right"))
        self.label_9.setText(_translate("Axes_tabwidget", "Length"))
        self.label_8.setText(_translate("Axes_tabwidget", "  Y tics:"))
        self.label_10.setText(_translate("Axes_tabwidget", "Label offset"))
        self.label_5.setText(_translate("Axes_tabwidget", "Label offset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AxesTics_tab), _translate("Axes_tabwidget", "Tics"))

