# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/axes_tabw.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Axes_tabwidget(object):
    def setupUi(self, Axes_tabwidget):
        Axes_tabwidget.setObjectName("Axes_tabwidget")
        Axes_tabwidget.resize(533, 344)
        self.gridLayout_3 = QtWidgets.QGridLayout(Axes_tabwidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Axes_tabwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Properties_tab = QtWidgets.QWidget()
        self.Properties_tab.setObjectName("Properties_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Properties_tab)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.AxesProperties_gridLayout = QtWidgets.QGridLayout()
        self.AxesProperties_gridLayout.setContentsMargins(11, 11, 11, 11)
        self.AxesProperties_gridLayout.setSpacing(6)
        self.AxesProperties_gridLayout.setObjectName("AxesProperties_gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.showLeft_checkBox = QtWidgets.QCheckBox(self.Properties_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showLeft_checkBox.sizePolicy().hasHeightForWidth())
        self.showLeft_checkBox.setSizePolicy(sizePolicy)
        self.showLeft_checkBox.setChecked(True)
        self.showLeft_checkBox.setObjectName("showLeft_checkBox")
        self.horizontalLayout_2.addWidget(self.showLeft_checkBox)
        self.showBottom_checkBox = QtWidgets.QCheckBox(self.Properties_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showBottom_checkBox.sizePolicy().hasHeightForWidth())
        self.showBottom_checkBox.setSizePolicy(sizePolicy)
        self.showBottom_checkBox.setChecked(True)
        self.showBottom_checkBox.setObjectName("showBottom_checkBox")
        self.horizontalLayout_2.addWidget(self.showBottom_checkBox)
        self.showRight_checkBox = QtWidgets.QCheckBox(self.Properties_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showRight_checkBox.sizePolicy().hasHeightForWidth())
        self.showRight_checkBox.setSizePolicy(sizePolicy)
        self.showRight_checkBox.setChecked(True)
        self.showRight_checkBox.setObjectName("showRight_checkBox")
        self.horizontalLayout_2.addWidget(self.showRight_checkBox)
        self.showTop_checkBox = QtWidgets.QCheckBox(self.Properties_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showTop_checkBox.sizePolicy().hasHeightForWidth())
        self.showTop_checkBox.setSizePolicy(sizePolicy)
        self.showTop_checkBox.setChecked(True)
        self.showTop_checkBox.setObjectName("showTop_checkBox")
        self.horizontalLayout_2.addWidget(self.showTop_checkBox)
        self.AxesProperties_gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 4)
        self.label_7 = QtWidgets.QLabel(self.Properties_tab)
        self.label_7.setObjectName("label_7")
        self.AxesProperties_gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.Properties_tab)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.AxesProperties_gridLayout.addWidget(self.label_14, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.Properties_tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.AxesProperties_gridLayout.addWidget(self.line, 0, 1, 1, 4)
        self.label_11 = QtWidgets.QLabel(self.Properties_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.AxesProperties_gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.Properties_tab)
        self.label_12.setObjectName("label_12")
        self.AxesProperties_gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.AxesProperties_gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.AxisBelow_checkBox = QtWidgets.QCheckBox(self.Properties_tab)
        self.AxisBelow_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AxisBelow_checkBox.setObjectName("AxisBelow_checkBox")
        self.AxesProperties_gridLayout.addWidget(self.AxisBelow_checkBox, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.Properties_tab)
        self.label_13.setObjectName("label_13")
        self.AxesProperties_gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.Properties_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox.setSingleStep(0.5)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.AxesProperties_gridLayout.addWidget(self.doubleSpinBox, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.Properties_tab)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.AxesProperties_gridLayout.addWidget(self.label_15, 3, 3, 1, 1)
        self.Grid_checkBox = QtWidgets.QCheckBox(self.Properties_tab)
        self.Grid_checkBox.setObjectName("Grid_checkBox")
        self.AxesProperties_gridLayout.addWidget(self.Grid_checkBox, 5, 0, 1, 1)
        self.gridLayout_4.addLayout(self.AxesProperties_gridLayout, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 3, 0, 1, 1)
        self.tabWidget.addTab(self.Properties_tab, "")
        self.AxesLabels_tab = QtWidgets.QWidget()
        self.AxesLabels_tab.setObjectName("AxesLabels_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.AxesLabels_tab)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AxesLabels_gridLayout = QtWidgets.QGridLayout()
        self.AxesLabels_gridLayout.setContentsMargins(11, 11, 11, 11)
        self.AxesLabels_gridLayout.setSpacing(6)
        self.AxesLabels_gridLayout.setObjectName("AxesLabels_gridLayout")
        self.XLabellabel = QtWidgets.QLabel(self.AxesLabels_tab)
        self.XLabellabel.setObjectName("XLabellabel")
        self.AxesLabels_gridLayout.addWidget(self.XLabellabel, 1, 0, 1, 1)
        self.XLabellineEdit = QtWidgets.QLineEdit(self.AxesLabels_tab)
        self.XLabellineEdit.setObjectName("XLabellineEdit")
        self.AxesLabels_gridLayout.addWidget(self.XLabellineEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.AxesLabels_tab)
        self.label_2.setObjectName("label_2")
        self.AxesLabels_gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.YLabellabel = QtWidgets.QLabel(self.AxesLabels_tab)
        self.YLabellabel.setObjectName("YLabellabel")
        self.AxesLabels_gridLayout.addWidget(self.YLabellabel, 2, 0, 1, 1)
        self.YLabellineEdit = QtWidgets.QLineEdit(self.AxesLabels_tab)
        self.YLabellineEdit.setObjectName("YLabellineEdit")
        self.AxesLabels_gridLayout.addWidget(self.YLabellineEdit, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.AxesLabels_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.AxesLabels_gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.XLabeloffsetdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesLabels_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XLabeloffsetdoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.XLabeloffsetdoubleSpinBox.setSizePolicy(sizePolicy)
        self.XLabeloffsetdoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XLabeloffsetdoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XLabeloffsetdoubleSpinBox.setObjectName("XLabeloffsetdoubleSpinBox")
        self.AxesLabels_gridLayout.addWidget(self.XLabeloffsetdoubleSpinBox, 1, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.AxesLabels_tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.AxesLabels_gridLayout.addWidget(self.line_2, 0, 1, 1, 3)
        self.Labelslabel = QtWidgets.QLabel(self.AxesLabels_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Labelslabel.setFont(font)
        self.Labelslabel.setObjectName("Labelslabel")
        self.AxesLabels_gridLayout.addWidget(self.Labelslabel, 0, 0, 1, 1)
        self.YLabeloffsetdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesLabels_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YLabeloffsetdoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.YLabeloffsetdoubleSpinBox.setSizePolicy(sizePolicy)
        self.YLabeloffsetdoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YLabeloffsetdoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YLabeloffsetdoubleSpinBox.setObjectName("YLabeloffsetdoubleSpinBox")
        self.AxesLabels_gridLayout.addWidget(self.YLabeloffsetdoubleSpinBox, 2, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.AxesLabels_tab)
        self.label_16.setObjectName("label_16")
        self.AxesLabels_gridLayout.addWidget(self.label_16, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.AxesLabels_gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Yrange_from_lineEdit = QtWidgets.QLineEdit(self.AxesLabels_tab)
        self.Yrange_from_lineEdit.setEnabled(False)
        self.Yrange_from_lineEdit.setObjectName("Yrange_from_lineEdit")
        self.gridLayout_2.addWidget(self.Yrange_from_lineEdit, 3, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.AxesLabels_tab)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 3, 2, 1, 1)
        self.Yrange_checkBox = QtWidgets.QCheckBox(self.AxesLabels_tab)
        self.Yrange_checkBox.setObjectName("Yrange_checkBox")
        self.gridLayout_2.addWidget(self.Yrange_checkBox, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.Xrange_checkBox = QtWidgets.QCheckBox(self.AxesLabels_tab)
        self.Xrange_checkBox.setObjectName("Xrange_checkBox")
        self.gridLayout_2.addWidget(self.Xrange_checkBox, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.Yrange_to_lineEdit = QtWidgets.QLineEdit(self.AxesLabels_tab)
        self.Yrange_to_lineEdit.setEnabled(False)
        self.Yrange_to_lineEdit.setObjectName("Yrange_to_lineEdit")
        self.gridLayout_2.addWidget(self.Yrange_to_lineEdit, 3, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.AxesLabels_tab)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 2, 1, 1)
        self.Xrange_to_lineEdit = QtWidgets.QLineEdit(self.AxesLabels_tab)
        self.Xrange_to_lineEdit.setEnabled(False)
        self.Xrange_to_lineEdit.setObjectName("Xrange_to_lineEdit")
        self.gridLayout_2.addWidget(self.Xrange_to_lineEdit, 2, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 4, 1, 1)
        self.Xrange_from_lineEdit = QtWidgets.QLineEdit(self.AxesLabels_tab)
        self.Xrange_from_lineEdit.setEnabled(False)
        self.Xrange_from_lineEdit.setObjectName("Xrange_from_lineEdit")
        self.gridLayout_2.addWidget(self.Xrange_from_lineEdit, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.AxesLabels_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 1, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.AxesLabels_tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 1, 1, 1, 4)
        self.LogY_checkBox = QtWidgets.QCheckBox(self.AxesLabels_tab)
        self.LogY_checkBox.setObjectName("LogY_checkBox")
        self.gridLayout_2.addWidget(self.LogY_checkBox, 4, 0, 1, 2)
        self.LogX_checkBox = QtWidgets.QCheckBox(self.AxesLabels_tab)
        self.LogX_checkBox.setObjectName("LogX_checkBox")
        self.gridLayout_2.addWidget(self.LogX_checkBox, 5, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 4, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.tabWidget.addTab(self.AxesLabels_tab, "")
        self.AxesTics_tab = QtWidgets.QWidget()
        self.AxesTics_tab.setObjectName("AxesTics_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.AxesTics_tab)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Tics_gridLayout = QtWidgets.QGridLayout()
        self.Tics_gridLayout.setContentsMargins(11, 11, 11, 11)
        self.Tics_gridLayout.setSpacing(6)
        self.Tics_gridLayout.setObjectName("Tics_gridLayout")
        self.line_3 = QtWidgets.QFrame(self.AxesTics_tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Tics_gridLayout.addWidget(self.line_3, 0, 1, 1, 6)
        self.XticsMinorLength_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.XticsMinorLength_doubleSpinBox.setEnabled(False)
        self.XticsMinorLength_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsMinorLength_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsMinorLength_doubleSpinBox.setObjectName("XticsMinorLength_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.XticsMinorLength_doubleSpinBox, 3, 4, 1, 1)
        self.YticsMinorWidth_label = QtWidgets.QLabel(self.AxesTics_tab)
        self.YticsMinorWidth_label.setEnabled(False)
        self.YticsMinorWidth_label.setObjectName("YticsMinorWidth_label")
        self.Tics_gridLayout.addWidget(self.YticsMinorWidth_label, 6, 5, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TicsLeft_checkBox = QtWidgets.QCheckBox(self.AxesTics_tab)
        self.TicsLeft_checkBox.setChecked(True)
        self.TicsLeft_checkBox.setObjectName("TicsLeft_checkBox")
        self.horizontalLayout.addWidget(self.TicsLeft_checkBox)
        self.TicsBottom_checkBox = QtWidgets.QCheckBox(self.AxesTics_tab)
        self.TicsBottom_checkBox.setChecked(True)
        self.TicsBottom_checkBox.setObjectName("TicsBottom_checkBox")
        self.horizontalLayout.addWidget(self.TicsBottom_checkBox)
        self.TicsRight_checkBox = QtWidgets.QCheckBox(self.AxesTics_tab)
        self.TicsRight_checkBox.setChecked(True)
        self.TicsRight_checkBox.setObjectName("TicsRight_checkBox")
        self.horizontalLayout.addWidget(self.TicsRight_checkBox)
        self.TicsTop_checkBox = QtWidgets.QCheckBox(self.AxesTics_tab)
        self.TicsTop_checkBox.setChecked(True)
        self.TicsTop_checkBox.setObjectName("TicsTop_checkBox")
        self.horizontalLayout.addWidget(self.TicsTop_checkBox)
        self.Tics_gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 6)
        self.XticsLength_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.XticsLength_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsLength_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsLength_doubleSpinBox.setObjectName("XticsLength_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.XticsLength_doubleSpinBox, 2, 4, 1, 1)
        self.XticsMinor_checkBox = QtWidgets.QCheckBox(self.AxesTics_tab)
        self.XticsMinor_checkBox.setObjectName("XticsMinor_checkBox")
        self.Tics_gridLayout.addWidget(self.XticsMinor_checkBox, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.AxesTics_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.Tics_gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.XticsWidth_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.XticsWidth_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsWidth_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsWidth_doubleSpinBox.setObjectName("XticsWidth_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.XticsWidth_doubleSpinBox, 2, 6, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.AxesTics_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.Tics_gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.Xtics_lineEdit = QtWidgets.QLineEdit(self.AxesTics_tab)
        self.Xtics_lineEdit.setObjectName("Xtics_lineEdit")
        self.Tics_gridLayout.addWidget(self.Xtics_lineEdit, 2, 1, 1, 2)
        self.XticsMinorWidth_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.XticsMinorWidth_doubleSpinBox.setEnabled(False)
        self.XticsMinorWidth_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsMinorWidth_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsMinorWidth_doubleSpinBox.setObjectName("XticsMinorWidth_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.XticsMinorWidth_doubleSpinBox, 3, 6, 1, 1)
        self.XticsMinorWidth_label = QtWidgets.QLabel(self.AxesTics_tab)
        self.XticsMinorWidth_label.setEnabled(False)
        self.XticsMinorWidth_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsMinorWidth_label.setObjectName("XticsMinorWidth_label")
        self.Tics_gridLayout.addWidget(self.XticsMinorWidth_label, 3, 5, 1, 1)
        self.XticsMinorLength_label = QtWidgets.QLabel(self.AxesTics_tab)
        self.XticsMinorLength_label.setEnabled(False)
        self.XticsMinorLength_label.setObjectName("XticsMinorLength_label")
        self.Tics_gridLayout.addWidget(self.XticsMinorLength_label, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.AxesTics_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.Tics_gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.AxesTics_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Tics_gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.AxesTics_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.Tics_gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.Ytics_lineEdit = QtWidgets.QLineEdit(self.AxesTics_tab)
        self.Ytics_lineEdit.setObjectName("Ytics_lineEdit")
        self.Tics_gridLayout.addWidget(self.Ytics_lineEdit, 5, 1, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.AxesTics_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.Tics_gridLayout.addWidget(self.label_18, 2, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.AxesTics_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.Tics_gridLayout.addWidget(self.label_6, 2, 3, 1, 1)
        self.YticsMinorLength_label = QtWidgets.QLabel(self.AxesTics_tab)
        self.YticsMinorLength_label.setEnabled(False)
        self.YticsMinorLength_label.setObjectName("YticsMinorLength_label")
        self.Tics_gridLayout.addWidget(self.YticsMinorLength_label, 6, 3, 1, 1)
        self.XticsOffset_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.XticsOffset_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsOffset_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsOffset_doubleSpinBox.setObjectName("XticsOffset_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.XticsOffset_doubleSpinBox, 4, 2, 1, 1)
        self.YticsOffset_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.YticsOffset_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsOffset_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsOffset_doubleSpinBox.setObjectName("YticsOffset_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.YticsOffset_doubleSpinBox, 7, 2, 1, 1)
        self.YticsMinorLength_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.YticsMinorLength_doubleSpinBox.setEnabled(False)
        self.YticsMinorLength_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsMinorLength_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsMinorLength_doubleSpinBox.setObjectName("YticsMinorLength_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.YticsMinorLength_doubleSpinBox, 6, 4, 1, 1)
        self.YticsWidth_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.YticsWidth_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsWidth_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsWidth_doubleSpinBox.setObjectName("YticsWidth_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.YticsWidth_doubleSpinBox, 5, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.AxesTics_tab)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.Tics_gridLayout.addWidget(self.label_9, 5, 3, 1, 1)
        self.XticsMinor_spinBox = QtWidgets.QSpinBox(self.AxesTics_tab)
        self.XticsMinor_spinBox.setEnabled(False)
        self.XticsMinor_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsMinor_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsMinor_spinBox.setObjectName("XticsMinor_spinBox")
        self.Tics_gridLayout.addWidget(self.XticsMinor_spinBox, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.AxesTics_tab)
        self.label_10.setObjectName("label_10")
        self.Tics_gridLayout.addWidget(self.label_10, 7, 1, 1, 1)
        self.YticsMinor_spinBox = QtWidgets.QSpinBox(self.AxesTics_tab)
        self.YticsMinor_spinBox.setEnabled(False)
        self.YticsMinor_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsMinor_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsMinor_spinBox.setObjectName("YticsMinor_spinBox")
        self.Tics_gridLayout.addWidget(self.YticsMinor_spinBox, 6, 2, 1, 1)
        self.YticsMinor_checkBox = QtWidgets.QCheckBox(self.AxesTics_tab)
        self.YticsMinor_checkBox.setObjectName("YticsMinor_checkBox")
        self.Tics_gridLayout.addWidget(self.YticsMinor_checkBox, 6, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.AxesTics_tab)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.Tics_gridLayout.addWidget(self.label_19, 5, 5, 1, 1)
        self.YticsMinorWidth_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.YticsMinorWidth_doubleSpinBox.setEnabled(False)
        self.YticsMinorWidth_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsMinorWidth_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsMinorWidth_doubleSpinBox.setObjectName("YticsMinorWidth_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.YticsMinorWidth_doubleSpinBox, 6, 6, 1, 1)
        self.YticsLength_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.AxesTics_tab)
        self.YticsLength_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsLength_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsLength_doubleSpinBox.setObjectName("YticsLength_doubleSpinBox")
        self.Tics_gridLayout.addWidget(self.YticsLength_doubleSpinBox, 5, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.AxesTics_tab)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.Tics_gridLayout.addWidget(self.label_20, 8, 3, 1, 1)
        self.verticalLayout_5.addLayout(self.Tics_gridLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.tabWidget.addTab(self.AxesTics_tab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Axes_tabwidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Axes_tabwidget)

    def retranslateUi(self, Axes_tabwidget):
        _translate = QtCore.QCoreApplication.translate
        self.showLeft_checkBox.setText(_translate("Axes_tabwidget", "Left"))
        self.showBottom_checkBox.setText(_translate("Axes_tabwidget", "Bottom"))
        self.showRight_checkBox.setText(_translate("Axes_tabwidget", "Right"))
        self.showTop_checkBox.setText(_translate("Axes_tabwidget", "Top"))
        self.label_7.setText(_translate("Axes_tabwidget", " Show axis:"))
        self.label_14.setText(_translate("Axes_tabwidget", "Axes:  "))
        self.label_11.setText(_translate("Axes_tabwidget", "PROPERTIES"))
        self.label_12.setText(_translate("Axes_tabwidget", " Line width:"))
        self.AxisBelow_checkBox.setText(_translate("Axes_tabwidget", "Axis below"))
        self.label_13.setText(_translate("Axes_tabwidget", " Colors:"))
        self.label_15.setText(_translate("Axes_tabwidget", "Canvas:  "))
        self.Grid_checkBox.setText(_translate("Axes_tabwidget", "Grid:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Properties_tab), _translate("Axes_tabwidget", "Properties"))
        self.XLabellabel.setText(_translate("Axes_tabwidget", " X label:"))
        self.label_2.setText(_translate("Axes_tabwidget", "   Offset: "))
        self.YLabellabel.setText(_translate("Axes_tabwidget", " Y label:"))
        self.label.setText(_translate("Axes_tabwidget", "   Offset: "))
        self.Labelslabel.setText(_translate("Axes_tabwidget", "LABELS"))
        self.label_16.setText(_translate("Axes_tabwidget", "   Color:  "))
        self.label_23.setText(_translate("Axes_tabwidget", "  :  "))
        self.Yrange_checkBox.setText(_translate("Axes_tabwidget", "Y Range:"))
        self.Xrange_checkBox.setText(_translate("Axes_tabwidget", "X Range:"))
        self.label_22.setText(_translate("Axes_tabwidget", "  :  "))
        self.label_21.setText(_translate("Axes_tabwidget", "AXIS RANGE "))
        self.LogY_checkBox.setText(_translate("Axes_tabwidget", "Logaritmic Y axis"))
        self.LogX_checkBox.setText(_translate("Axes_tabwidget", "Logaritmic X axis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AxesLabels_tab), _translate("Axes_tabwidget", "Labels - Range"))
        self.YticsMinorWidth_label.setText(_translate("Axes_tabwidget", "   Width: "))
        self.TicsLeft_checkBox.setText(_translate("Axes_tabwidget", "Left"))
        self.TicsBottom_checkBox.setText(_translate("Axes_tabwidget", "Bottom"))
        self.TicsRight_checkBox.setText(_translate("Axes_tabwidget", "Right"))
        self.TicsTop_checkBox.setText(_translate("Axes_tabwidget", "Top"))
        self.XticsMinor_checkBox.setText(_translate("Axes_tabwidget", " Minor tics"))
        self.label_5.setText(_translate("Axes_tabwidget", "Label offset"))
        self.label_17.setText(_translate("Axes_tabwidget", " Show tics: "))
        self.XticsMinorWidth_label.setText(_translate("Axes_tabwidget", "   Width: "))
        self.XticsMinorLength_label.setText(_translate("Axes_tabwidget", "   Length: "))
        self.label_4.setText(_translate("Axes_tabwidget", " X tics:"))
        self.label_3.setText(_translate("Axes_tabwidget", "TICS      "))
        self.label_8.setText(_translate("Axes_tabwidget", " Y tics:"))
        self.label_18.setText(_translate("Axes_tabwidget", "   Width: "))
        self.label_6.setText(_translate("Axes_tabwidget", "   Length: "))
        self.YticsMinorLength_label.setText(_translate("Axes_tabwidget", "   Length: "))
        self.label_9.setText(_translate("Axes_tabwidget", "   Length: "))
        self.label_10.setText(_translate("Axes_tabwidget", "Label offset"))
        self.YticsMinor_checkBox.setText(_translate("Axes_tabwidget", "Minor tics"))
        self.label_19.setText(_translate("Axes_tabwidget", "   Width: "))
        self.label_20.setText(_translate("Axes_tabwidget", "   Color: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AxesTics_tab), _translate("Axes_tabwidget", "Tics"))

