# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/plot1d.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Plot1D_Window(object):
    def setupUi(self, Plot1D_Window):
        Plot1D_Window.setObjectName("Plot1D_Window")
        Plot1D_Window.resize(654, 439)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Plot1D_Window)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Main_gridLayout = QtWidgets.QGridLayout()
        self.Main_gridLayout.setContentsMargins(11, 11, 11, 11)
        self.Main_gridLayout.setSpacing(6)
        self.Main_gridLayout.setObjectName("Main_gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(Plot1D_Window)
        self.pushButton_2.setObjectName("pushButton_2")
        self.Main_gridLayout.addWidget(self.pushButton_2, 2, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Plot1D_Window)
        self.pushButton.setObjectName("pushButton")
        self.Main_gridLayout.addWidget(self.pushButton, 2, 4, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Plot1D_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageGeneral = QtWidgets.QWidget()
        self.pageGeneral.setObjectName("pageGeneral")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.pageGeneral)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.GeneralSettings_gridLayout = QtWidgets.QGridLayout()
        self.GeneralSettings_gridLayout.setContentsMargins(11, 11, 11, 11)
        self.GeneralSettings_gridLayout.setSpacing(6)
        self.GeneralSettings_gridLayout.setObjectName("GeneralSettings_gridLayout")
        self.Generallabel = QtWidgets.QLabel(self.pageGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Generallabel.sizePolicy().hasHeightForWidth())
        self.Generallabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Generallabel.setFont(font)
        self.Generallabel.setObjectName("Generallabel")
        self.GeneralSettings_gridLayout.addWidget(self.Generallabel, 0, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.pageGeneral)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.GeneralSettings_gridLayout.addWidget(self.line_4, 0, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.GeneralSettings_gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.gridLayout_11.addLayout(self.GeneralSettings_gridLayout, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem1, 5, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageGeneral)
        self.pageLegend = QtWidgets.QWidget()
        self.pageLegend.setObjectName("pageLegend")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pageLegend)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_26 = QtWidgets.QLabel(self.pageLegend)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_9.addWidget(self.label_26, 1, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.pageLegend)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_9.addWidget(self.line_6, 1, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 2, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageLegend)
        self.pageDataEMPTY = QtWidgets.QWidget()
        self.pageDataEMPTY.setObjectName("pageDataEMPTY")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pageDataEMPTY)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_13 = QtWidgets.QLabel(self.pageDataEMPTY)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.pageDataEMPTY)
        self.pageData1 = QtWidgets.QWidget()
        self.pageData1.setObjectName("pageData1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pageData1)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(492, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.pageData1)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageData1)
        self.Main_gridLayout.addWidget(self.stackedWidget, 1, 2, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Main_gridLayout.addItem(spacerItem5, 2, 2, 1, 1)
        self.listWidget = QtWidgets.QListWidget(Plot1D_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        self.Main_gridLayout.addWidget(self.listWidget, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.Main_gridLayout.addItem(spacerItem6, 2, 1, 1, 1)
        self.horizontalLayout.addLayout(self.Main_gridLayout)

        self.retranslateUi(Plot1D_Window)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Plot1D_Window)

    def retranslateUi(self, Plot1D_Window):
        _translate = QtCore.QCoreApplication.translate
        Plot1D_Window.setWindowTitle(_translate("Plot1D_Window", "Form"))
        self.pushButton_2.setText(_translate("Plot1D_Window", "Reset"))
        self.pushButton.setText(_translate("Plot1D_Window", "Plot"))
        self.Generallabel.setText(_translate("Plot1D_Window", "GENERAL SETTINGS"))
        self.label_26.setText(_translate("Plot1D_Window", "LEGEND"))
        self.label_13.setText(_translate("Plot1D_Window", "EMPTY DATA PAGE"))
        self.label_14.setText(_translate("Plot1D_Window", "Plot #1"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Plot1D_Window", "General "))
        item = self.listWidget.item(1)
        item.setText(_translate("Plot1D_Window", "Axes"))
        item = self.listWidget.item(2)
        item.setText(_translate("Plot1D_Window", "Legend"))
        item = self.listWidget.item(3)
        item.setText(_translate("Plot1D_Window", "Data"))
        item = self.listWidget.item(4)
        item.setText(_translate("Plot1D_Window", "    Plot1"))
        self.listWidget.setSortingEnabled(__sortingEnabled)

