# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/plot1d_tabw.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Plot1D_tabwidget(object):
    def setupUi(self, Plot1D_tabwidget):
        Plot1D_tabwidget.setObjectName("Plot1D_tabwidget")
        Plot1D_tabwidget.resize(565, 391)
        self.gridLayout_3 = QtWidgets.QGridLayout(Plot1D_tabwidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Plot1D_tabwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.Data_tab = QtWidgets.QWidget()
        self.Data_tab.setObjectName("Data_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Data_tab)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.dataXfunc_lineEdit = QtWidgets.QLineEdit(self.Data_tab)
        self.dataXfunc_lineEdit.setObjectName("dataXfunc_lineEdit")
        self.gridLayout_5.addWidget(self.dataXfunc_lineEdit, 2, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.Data_tab)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_13 = QtWidgets.QLabel(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.X_file_comboBox = QtWidgets.QComboBox(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X_file_comboBox.sizePolicy().hasHeightForWidth())
        self.X_file_comboBox.setSizePolicy(sizePolicy)
        self.X_file_comboBox.setObjectName("X_file_comboBox")
        self.gridLayout_5.addWidget(self.X_file_comboBox, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 1, 1, 1)
        self.dataYfunc_lineEdit = QtWidgets.QLineEdit(self.Data_tab)
        self.dataYfunc_lineEdit.setObjectName("dataYfunc_lineEdit")
        self.gridLayout_5.addWidget(self.dataYfunc_lineEdit, 3, 3, 1, 1)
        self.Y_file_comboBox = QtWidgets.QComboBox(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Y_file_comboBox.sizePolicy().hasHeightForWidth())
        self.Y_file_comboBox.setSizePolicy(sizePolicy)
        self.Y_file_comboBox.setObjectName("Y_file_comboBox")
        self.gridLayout_5.addWidget(self.Y_file_comboBox, 3, 1, 1, 1)
        self.Yerr_file_comboBox = QtWidgets.QComboBox(self.Data_tab)
        self.Yerr_file_comboBox.setEnabled(False)
        self.Yerr_file_comboBox.setObjectName("Yerr_file_comboBox")
        self.gridLayout_5.addWidget(self.Yerr_file_comboBox, 5, 1, 1, 1)
        self.Xerr_file_comboBox = QtWidgets.QComboBox(self.Data_tab)
        self.Xerr_file_comboBox.setEnabled(False)
        self.Xerr_file_comboBox.setObjectName("Xerr_file_comboBox")
        self.gridLayout_5.addWidget(self.Xerr_file_comboBox, 4, 1, 1, 1)
        self.Xerr_checkBox = QtWidgets.QCheckBox(self.Data_tab)
        self.Xerr_checkBox.setObjectName("Xerr_checkBox")
        self.gridLayout_5.addWidget(self.Xerr_checkBox, 4, 0, 1, 1)
        self.Xerr_col_comboBox = QtWidgets.QComboBox(self.Data_tab)
        self.Xerr_col_comboBox.setEnabled(False)
        self.Xerr_col_comboBox.setObjectName("Xerr_col_comboBox")
        self.gridLayout_5.addWidget(self.Xerr_col_comboBox, 4, 2, 1, 1)
        self.X_col_comboBox = QtWidgets.QComboBox(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X_col_comboBox.sizePolicy().hasHeightForWidth())
        self.X_col_comboBox.setSizePolicy(sizePolicy)
        self.X_col_comboBox.setObjectName("X_col_comboBox")
        self.gridLayout_5.addWidget(self.X_col_comboBox, 2, 2, 1, 1)
        self.Y_col_comboBox = QtWidgets.QComboBox(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Y_col_comboBox.sizePolicy().hasHeightForWidth())
        self.Y_col_comboBox.setSizePolicy(sizePolicy)
        self.Y_col_comboBox.setObjectName("Y_col_comboBox")
        self.gridLayout_5.addWidget(self.Y_col_comboBox, 3, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.Data_tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.Data_tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 0, 1, 1, 3)
        self.label_16 = QtWidgets.QLabel(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 0, 1, 1)
        self.Yerr_col_comboBox = QtWidgets.QComboBox(self.Data_tab)
        self.Yerr_col_comboBox.setEnabled(False)
        self.Yerr_col_comboBox.setObjectName("Yerr_col_comboBox")
        self.gridLayout_5.addWidget(self.Yerr_col_comboBox, 5, 2, 1, 1)
        self.Yerr_checkBox = QtWidgets.QCheckBox(self.Data_tab)
        self.Yerr_checkBox.setObjectName("Yerr_checkBox")
        self.gridLayout_5.addWidget(self.Yerr_checkBox, 5, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.Rows_from_spinBox = QtWidgets.QSpinBox(self.Data_tab)
        self.Rows_from_spinBox.setEnabled(False)
        self.Rows_from_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Rows_from_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Rows_from_spinBox.setObjectName("Rows_from_spinBox")
        self.gridLayout.addWidget(self.Rows_from_spinBox, 1, 3, 1, 1)
        self.Rows_all_checkBox = QtWidgets.QCheckBox(self.Data_tab)
        self.Rows_all_checkBox.setChecked(True)
        self.Rows_all_checkBox.setAutoExclusive(True)
        self.Rows_all_checkBox.setObjectName("Rows_all_checkBox")
        self.gridLayout.addWidget(self.Rows_all_checkBox, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.Data_tab)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 1, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 6, 1, 1)
        self.Rows_from_checkBox = QtWidgets.QCheckBox(self.Data_tab)
        self.Rows_from_checkBox.setAutoExclusive(True)
        self.Rows_from_checkBox.setObjectName("Rows_from_checkBox")
        self.gridLayout.addWidget(self.Rows_from_checkBox, 1, 2, 1, 1)
        self.Rows_to_spinBox = QtWidgets.QSpinBox(self.Data_tab)
        self.Rows_to_spinBox.setEnabled(False)
        self.Rows_to_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Rows_to_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Rows_to_spinBox.setObjectName("Rows_to_spinBox")
        self.gridLayout.addWidget(self.Rows_to_spinBox, 1, 5, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.Data_tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 1, 1, 6)
        self.label_19 = QtWidgets.QLabel(self.Data_tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 2, 0, 1, 1)
        self.Rows_every_spinBox = QtWidgets.QSpinBox(self.Data_tab)
        self.Rows_every_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Rows_every_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Rows_every_spinBox.setMaximum(10000)
        self.Rows_every_spinBox.setProperty("value", 1)
        self.Rows_every_spinBox.setObjectName("Rows_every_spinBox")
        self.gridLayout.addWidget(self.Rows_every_spinBox, 2, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.tabWidget.addTab(self.Data_tab, "")
        self.Markers_tab = QtWidgets.QWidget()
        self.Markers_tab.setObjectName("Markers_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Markers_tab)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Marker_gridLayout = QtWidgets.QGridLayout()
        self.Marker_gridLayout.setContentsMargins(11, 11, 11, 11)
        self.Marker_gridLayout.setSpacing(6)
        self.Marker_gridLayout.setObjectName("Marker_gridLayout")
        self.line_6 = QtWidgets.QFrame(self.Markers_tab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.Marker_gridLayout.addWidget(self.line_6, 0, 1, 1, 4)
        self.Marksize_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.Markers_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Marksize_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.Marksize_doubleSpinBox.setSizePolicy(sizePolicy)
        self.Marksize_doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Marksize_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Marksize_doubleSpinBox.setObjectName("Marksize_doubleSpinBox")
        self.Marker_gridLayout.addWidget(self.Marksize_doubleSpinBox, 1, 3, 1, 1)
        self.Markers_label = QtWidgets.QLabel(self.Markers_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Markers_label.sizePolicy().hasHeightForWidth())
        self.Markers_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Markers_label.setFont(font)
        self.Markers_label.setObjectName("Markers_label")
        self.Marker_gridLayout.addWidget(self.Markers_label, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.Markers_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.Marker_gridLayout.addWidget(self.label_25, 1, 2, 1, 1)
        self.MarkType_comboBox = QtWidgets.QComboBox(self.Markers_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MarkType_comboBox.sizePolicy().hasHeightForWidth())
        self.MarkType_comboBox.setSizePolicy(sizePolicy)
        self.MarkType_comboBox.setObjectName("MarkType_comboBox")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.MarkType_comboBox.addItem("")
        self.Marker_gridLayout.addWidget(self.MarkType_comboBox, 1, 1, 1, 1)
        self.Marktype_label = QtWidgets.QLabel(self.Markers_tab)
        self.Marktype_label.setObjectName("Marktype_label")
        self.Marker_gridLayout.addWidget(self.Marktype_label, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Marker_gridLayout.addItem(spacerItem2, 2, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Markers_tab)
        self.label_2.setObjectName("label_2")
        self.Marker_gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.Marker_gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.tabWidget.addTab(self.Markers_tab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Plot1D_tabwidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Plot1D_tabwidget)

    def retranslateUi(self, Plot1D_tabwidget):
        _translate = QtCore.QCoreApplication.translate
        Plot1D_tabwidget.setWindowTitle(_translate("Plot1D_tabwidget", "Form"))
        self.label_24.setText(_translate("Plot1D_tabwidget", "f(x)"))
        self.label_13.setText(_translate("Plot1D_tabwidget", " Data X: "))
        self.label_15.setText(_translate("Plot1D_tabwidget", "File "))
        self.Xerr_checkBox.setText(_translate("Plot1D_tabwidget", " Error X:"))
        self.label_14.setText(_translate("Plot1D_tabwidget", " Data Y: "))
        self.label_16.setText(_translate("Plot1D_tabwidget", "Column"))
        self.label_17.setText(_translate("Plot1D_tabwidget", "DATA SERIES"))
        self.Yerr_checkBox.setText(_translate("Plot1D_tabwidget", " Error Y:"))
        self.Rows_all_checkBox.setText(_translate("Plot1D_tabwidget", "All"))
        self.label_20.setText(_translate("Plot1D_tabwidget", "to"))
        self.label_18.setText(_translate("Plot1D_tabwidget", "ROWS           "))
        self.Rows_from_checkBox.setText(_translate("Plot1D_tabwidget", "From row"))
        self.label_19.setText(_translate("Plot1D_tabwidget", " Every"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Data_tab), _translate("Plot1D_tabwidget", "Data"))
        self.Markers_label.setText(_translate("Plot1D_tabwidget", "MARKERS"))
        self.label_25.setText(_translate("Plot1D_tabwidget", "       Size:"))
        self.MarkType_comboBox.setItemText(0, _translate("Plot1D_tabwidget", "Pixel"))
        self.MarkType_comboBox.setItemText(1, _translate("Plot1D_tabwidget", "Point"))
        self.MarkType_comboBox.setItemText(2, _translate("Plot1D_tabwidget", "Plus"))
        self.MarkType_comboBox.setItemText(3, _translate("Plot1D_tabwidget", "Cross"))
        self.MarkType_comboBox.setItemText(4, _translate("Plot1D_tabwidget", "Star"))
        self.MarkType_comboBox.setItemText(5, _translate("Plot1D_tabwidget", "Circle"))
        self.MarkType_comboBox.setItemText(6, _translate("Plot1D_tabwidget", "Triangle down"))
        self.MarkType_comboBox.setItemText(7, _translate("Plot1D_tabwidget", "Triangle up"))
        self.MarkType_comboBox.setItemText(8, _translate("Plot1D_tabwidget", "Triangle left"))
        self.MarkType_comboBox.setItemText(9, _translate("Plot1D_tabwidget", "Triangle right"))
        self.MarkType_comboBox.setItemText(10, _translate("Plot1D_tabwidget", "Square"))
        self.MarkType_comboBox.setItemText(11, _translate("Plot1D_tabwidget", "Diamond"))
        self.MarkType_comboBox.setItemText(12, _translate("Plot1D_tabwidget", "Diamond (thin)"))
        self.MarkType_comboBox.setItemText(13, _translate("Plot1D_tabwidget", "Pentagon"))
        self.MarkType_comboBox.setItemText(14, _translate("Plot1D_tabwidget", "Hexagon"))
        self.MarkType_comboBox.setItemText(15, _translate("Plot1D_tabwidget", "Hexagon Flat"))
        self.MarkType_comboBox.setItemText(16, _translate("Plot1D_tabwidget", "Octagon"))
        self.MarkType_comboBox.setItemText(17, _translate("Plot1D_tabwidget", "Vertical line"))
        self.MarkType_comboBox.setItemText(18, _translate("Plot1D_tabwidget", "Horizontal line"))
        self.MarkType_comboBox.setItemText(19, _translate("Plot1D_tabwidget", "Tri down"))
        self.MarkType_comboBox.setItemText(20, _translate("Plot1D_tabwidget", "Tri up"))
        self.MarkType_comboBox.setItemText(21, _translate("Plot1D_tabwidget", "Tri left"))
        self.MarkType_comboBox.setItemText(22, _translate("Plot1D_tabwidget", "Tri right"))
        self.Marktype_label.setText(_translate("Plot1D_tabwidget", " Type:"))
        self.label_2.setText(_translate("Plot1D_tabwidget", " Edge:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Markers_tab), _translate("Plot1D_tabwidget", "Markers"))

