# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/plot1d_tabw.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Plot1D_tabwidget(object):
    def setupUi(self, Plot1D_tabwidget):
        Plot1D_tabwidget.setObjectName("Plot1D_tabwidget")
        Plot1D_tabwidget.resize(565, 485)
        self.gridLayout_3 = QtWidgets.QGridLayout(Plot1D_tabwidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Plot1D_tabwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.Data_tab = QtWidgets.QWidget()
        self.Data_tab.setObjectName("Data_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Data_tab)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_15 = QtWidgets.QLabel(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 1, 1, 1)
        self.X_file_comboBox = QtWidgets.QComboBox(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X_file_comboBox.sizePolicy().hasHeightForWidth())
        self.X_file_comboBox.setSizePolicy(sizePolicy)
        self.X_file_comboBox.setObjectName("X_file_comboBox")
        self.gridLayout_5.addWidget(self.X_file_comboBox, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.Y_file_comboBox = QtWidgets.QComboBox(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Y_file_comboBox.sizePolicy().hasHeightForWidth())
        self.Y_file_comboBox.setSizePolicy(sizePolicy)
        self.Y_file_comboBox.setObjectName("Y_file_comboBox")
        self.gridLayout_5.addWidget(self.Y_file_comboBox, 3, 1, 1, 1)
        self.X_col_comboBox = QtWidgets.QComboBox(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X_col_comboBox.sizePolicy().hasHeightForWidth())
        self.X_col_comboBox.setSizePolicy(sizePolicy)
        self.X_col_comboBox.setObjectName("X_col_comboBox")
        self.gridLayout_5.addWidget(self.X_col_comboBox, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.Data_tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 3, 0, 1, 1)
        self.Y_col_comboBox = QtWidgets.QComboBox(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Y_col_comboBox.sizePolicy().hasHeightForWidth())
        self.Y_col_comboBox.setSizePolicy(sizePolicy)
        self.Y_col_comboBox.setObjectName("Y_col_comboBox")
        self.gridLayout_5.addWidget(self.Y_col_comboBox, 3, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.Data_tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 0, 1, 1, 3)
        self.label_24 = QtWidgets.QLabel(self.Data_tab)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.dataYfunc_lineEdit = QtWidgets.QLineEdit(self.Data_tab)
        self.dataYfunc_lineEdit.setObjectName("dataYfunc_lineEdit")
        self.gridLayout_5.addWidget(self.dataYfunc_lineEdit, 3, 3, 1, 1)
        self.dataXfunc_lineEdit = QtWidgets.QLineEdit(self.Data_tab)
        self.dataXfunc_lineEdit.setObjectName("dataXfunc_lineEdit")
        self.gridLayout_5.addWidget(self.dataXfunc_lineEdit, 2, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.Rows_from_spinBox = QtWidgets.QSpinBox(self.Data_tab)
        self.Rows_from_spinBox.setEnabled(False)
        self.Rows_from_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Rows_from_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Rows_from_spinBox.setObjectName("Rows_from_spinBox")
        self.gridLayout.addWidget(self.Rows_from_spinBox, 1, 3, 1, 1)
        self.Rows_all_checkBox = QtWidgets.QCheckBox(self.Data_tab)
        self.Rows_all_checkBox.setChecked(True)
        self.Rows_all_checkBox.setAutoExclusive(True)
        self.Rows_all_checkBox.setObjectName("Rows_all_checkBox")
        self.gridLayout.addWidget(self.Rows_all_checkBox, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.Data_tab)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 1, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.Data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 6, 1, 1)
        self.Rows_from_checkBox = QtWidgets.QCheckBox(self.Data_tab)
        self.Rows_from_checkBox.setAutoExclusive(True)
        self.Rows_from_checkBox.setObjectName("Rows_from_checkBox")
        self.gridLayout.addWidget(self.Rows_from_checkBox, 1, 2, 1, 1)
        self.Rows_to_spinBox = QtWidgets.QSpinBox(self.Data_tab)
        self.Rows_to_spinBox.setEnabled(False)
        self.Rows_to_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Rows_to_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Rows_to_spinBox.setObjectName("Rows_to_spinBox")
        self.gridLayout.addWidget(self.Rows_to_spinBox, 1, 5, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.Data_tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 1, 1, 6)
        self.label_19 = QtWidgets.QLabel(self.Data_tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 2, 0, 1, 1)
        self.Rows_every_spinBox = QtWidgets.QSpinBox(self.Data_tab)
        self.Rows_every_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Rows_every_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Rows_every_spinBox.setMaximum(10000)
        self.Rows_every_spinBox.setProperty("value", 1)
        self.Rows_every_spinBox.setObjectName("Rows_every_spinBox")
        self.gridLayout.addWidget(self.Rows_every_spinBox, 2, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.Data_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.Labelslabel_2 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Labelslabel_2.setFont(font)
        self.Labelslabel_2.setObjectName("Labelslabel_2")
        self.gridLayout_9.addWidget(self.Labelslabel_2, 0, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.tab_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_9.addWidget(self.line_6, 0, 1, 1, 3)
        self.YLabellabel_2 = QtWidgets.QLabel(self.tab_2)
        self.YLabellabel_2.setObjectName("YLabellabel_2")
        self.gridLayout_9.addWidget(self.YLabellabel_2, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.gridLayout_9.addWidget(self.label_25, 1, 2, 1, 1)
        self.LabelFonttoolButton_2 = QtWidgets.QToolButton(self.tab_2)
        self.LabelFonttoolButton_2.setObjectName("LabelFonttoolButton_2")
        self.gridLayout_9.addWidget(self.LabelFonttoolButton_2, 3, 1, 1, 1)
        self.XLabellineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.XLabellineEdit_2.setObjectName("XLabellineEdit_2")
        self.gridLayout_9.addWidget(self.XLabellineEdit_2, 1, 1, 1, 1)
        self.Fontlabel_2 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fontlabel_2.sizePolicy().hasHeightForWidth())
        self.Fontlabel_2.setSizePolicy(sizePolicy)
        self.Fontlabel_2.setObjectName("Fontlabel_2")
        self.gridLayout_9.addWidget(self.Fontlabel_2, 3, 0, 1, 1)
        self.XLabeloffsetdoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XLabeloffsetdoubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.XLabeloffsetdoubleSpinBox_2.setSizePolicy(sizePolicy)
        self.XLabeloffsetdoubleSpinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XLabeloffsetdoubleSpinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XLabeloffsetdoubleSpinBox_2.setObjectName("XLabeloffsetdoubleSpinBox_2")
        self.gridLayout_9.addWidget(self.XLabeloffsetdoubleSpinBox_2, 1, 3, 1, 1)
        self.YLabellineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.YLabellineEdit_2.setObjectName("YLabellineEdit_2")
        self.gridLayout_9.addWidget(self.YLabellineEdit_2, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_9.addWidget(self.label_26, 2, 2, 1, 1)
        self.YLabeloffsetdoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.YLabeloffsetdoubleSpinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YLabeloffsetdoubleSpinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YLabeloffsetdoubleSpinBox_2.setObjectName("YLabeloffsetdoubleSpinBox_2")
        self.gridLayout_9.addWidget(self.YLabeloffsetdoubleSpinBox_2, 2, 3, 1, 1)
        self.XLabellabel_2 = QtWidgets.QLabel(self.tab_2)
        self.XLabellabel_2.setObjectName("XLabellabel_2")
        self.gridLayout_9.addWidget(self.XLabellabel_2, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_9)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Plot1D_tabwidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Plot1D_tabwidget)

    def retranslateUi(self, Plot1D_tabwidget):
        _translate = QtCore.QCoreApplication.translate
        Plot1D_tabwidget.setWindowTitle(_translate("Plot1D_tabwidget", "Form"))
        self.label_15.setText(_translate("Plot1D_tabwidget", "File "))
        self.label_13.setText(_translate("Plot1D_tabwidget", " Data X: "))
        self.label_14.setText(_translate("Plot1D_tabwidget", " Data Y: "))
        self.label_16.setText(_translate("Plot1D_tabwidget", "Column"))
        self.label_17.setText(_translate("Plot1D_tabwidget", "DATA SERIES"))
        self.label_24.setText(_translate("Plot1D_tabwidget", "f(x)"))
        self.Rows_all_checkBox.setText(_translate("Plot1D_tabwidget", "All"))
        self.label_20.setText(_translate("Plot1D_tabwidget", "to"))
        self.label_18.setText(_translate("Plot1D_tabwidget", "ROWS           "))
        self.Rows_from_checkBox.setText(_translate("Plot1D_tabwidget", "From row"))
        self.label_19.setText(_translate("Plot1D_tabwidget", " Every"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Data_tab), _translate("Plot1D_tabwidget", "Data"))
        self.Labelslabel_2.setText(_translate("Plot1D_tabwidget", "MARKERS"))
        self.YLabellabel_2.setText(_translate("Plot1D_tabwidget", "  Y label:"))
        self.label_25.setText(_translate("Plot1D_tabwidget", "Offset"))
        self.LabelFonttoolButton_2.setText(_translate("Plot1D_tabwidget", "Helvetica, 12 pt"))
        self.Fontlabel_2.setText(_translate("Plot1D_tabwidget", "  Font:"))
        self.label_26.setText(_translate("Plot1D_tabwidget", "Offset"))
        self.XLabellabel_2.setText(_translate("Plot1D_tabwidget", "  X label:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Plot1D_tabwidget", "Markers"))

